version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  device_camera:
    build:
      context: ./docker
      dockerfile: Dockerfile.devices
    container_name: device_camera
    command: python device_camera.py

  device_light:
    build:
      context: ./docker
      dockerfile: Dockerfile.devices
    container_name: device_light
    command: python device_light.py

  device_temperature:
    build:
      context: ./docker
      dockerfile: Dockerfile.devices
    container_name: device_temperature
    command: python device_temperature.py

  ids:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ids
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./ids:/app/ids
      - ./logs:/logs
    depends_on:
      - mqtt-broker
    command: python ids/ids.py

  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: train
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./scripts:/app/scripts
    command: python /app/scripts/train_model.py