# Dockerfile.train
FROM tensorflow/tensorflow:2.9.0

WORKDIR /app
COPY . /app

RUN pip install numpy==1.21.0 pandas==1.3.0 scikit-learn==1.2.0 h5py==3.1.0 joblib==1.1.0 seaborn==0.11.1

CMD ["python", "/app/scripts/ddos_detector_randomforest.py"]