# Dockerfile.ddos

# Specify a base image with Python
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the simulator script and other necessary files into the container
COPY ddos/test_traffic.py /app/ddos/

# Install required Python packages if any
RUN pip install scapy

# Set the command to run the script
CMD ["python", "ddos/test_traffic.py"]
