FROM python:3.9-slim

WORKDIR /app

# Copy all the device scripts (you can remove 'device.py' if you don't need it)
COPY device_camera.py /app/
COPY device_light.py /app/
COPY device_temperature.py /app/

# Install any necessary dependencies for MQTT and network communications
RUN pip install paho-mqtt==1.5.1 scapy

# Default command (this is overridden by docker-compose command for each specific device)
CMD ["python", "device_camera.py"]